[package]
name = "binaural-explorer-web"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
glam.workspace = true
hrtf = { path = "../hrtf" }
wasm-bindgen.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = ["HtmlCanvasElement"] }
wgpu = { workspace = true, default-features = false, features = ["webgl", "webgpu", "wgsl"] }

[lints]
workspace = true
